name: text_recognition_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  path: ^1.9.0
  image_gallery_saver: '^2.0.3'
  permission_handler: ^10.2.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_barcode_scanning: ^0.12.0
  paddle_ocr: ^0.0.5
  flutter_vision: ^1.1.4
  mongo_dart: ^0.9.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
